/**
 * generate-vrchat.js
 * Scans the VRC_PHOTOS folder and generates a static `vrchat-photos.js`
 * data file that the VRChat photo page loads directly.
 *
 * This keeps the site static and GitHub Pages-compatible: you drop any
 * number of images into VRC_PHOTOS and subfolders, run `node generate-vrchat.js`,
 * commit the generated `vrchat-photos.js`, and push.
 *
 * STRUCTURE:
 *   VRC_PHOTOS/
 *     Casual Photos/
 *       photo1.png
 *       photo2.png
 *     Group Photos/
 *       photo3.png
 *     root-photo.png
 *
 * Each top-level folder becomes a VRChat category. Files directly inside
 * VRC_PHOTOS are grouped into an "Unsorted" category.
 *
 * Usage:
 *   node generate-vrchat.js
 *
 * Outputs: vrchat-photos.js  (a static JS file exposing window.VRC_PHOTOS)
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PHOTO_DIR = path.join(ROOT, 'VRC_PHOTOS');
const OUTPUT = path.join(ROOT, 'vrchat-photos.js');

// Supported image extensions (case-insensitive)
const IMAGE_EXTS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp', '.svg', '.avif'
]);

// Map category folder names to friendly labels shown in the UI.
// Add new entries here as you create subfolders inside VRC_PHOTOS.
const CATEGORY_LABELS = {
  'Casual Photos': 'Casual Photos',
  'Group Photos': 'Group Photos'
};

function isImage(file) {
  return IMAGE_EXTS.has(path.extname(file).toLowerCase());
}

function labelFor(folderName) {
  return CATEGORY_LABELS[folderName] || folderName.replace(/_/g, ' ');
}

function urlEncode(name) {
  return name.split(path.sep).map(encodeURIComponent).join('/');
}

function buildCategory(name, files) {
  return {
    name: name.replace(/\s+/g, '-').toLowerCase(),
    label: labelFor(name),
    photos: files.map((file) => 'VRC_PHOTOS/' + urlEncode(path.join(name, file)))
  };
}

function build() {
  const categories = [];

  if (!fs.existsSync(PHOTO_DIR)) {
    console.log('VRC_PHOTOS folder not found. Create it and add images or folders.');
  } else {
    const entries = fs.readdirSync(PHOTO_DIR, { withFileTypes: true });
    const rootFiles = entries
      .filter((entry) => entry.isFile() && isImage(entry.name))
      .sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }))
      .map((entry) => entry.name);

    if (rootFiles.length > 0) {
      categories.push(buildCategory('Unsorted', rootFiles));
    }

    const folders = entries
      .filter((entry) => entry.isDirectory())
      .sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));

    for (const folder of folders) {
      const folderPath = path.join(PHOTO_DIR, folder.name);
      const files = fs.readdirSync(folderPath)
        .filter(isImage)
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

      if (files.length === 0) {
        console.log(`Skipping category "${folder.name}" — no images found.`);
        continue;
      }

      categories.push(buildCategory(folder.name, files));
    }
  }

  const jsContent =
    '/* ============================================================\n' +
    '   AUTO-GENERATED by generate-vrchat.js — do not edit directly.\n' +
    '   Run "node generate-vrchat.js" to rebuild from VRC_PHOTOS.\n' +
    '   Data structure: [{ name, label, photos: [ "path/to/photo.png" ] }]\n' +
    '   ============================================================ */\n' +
    'window.VRC_PHOTOS = ' + JSON.stringify(categories, null, 2) + ';\n';

  fs.writeFileSync(OUTPUT, jsContent, 'utf8');
  console.log(`✅ Generated ${OUTPUT}`);
  console.log(`   ${categories.length} category${categories.length === 1 ? '' : 'ies'} found in VRC_PHOTOS:`);
  categories.forEach((category) => {
    console.log(`   - ${category.label} (${category.photos.length} photo${category.photos.length !== 1 ? 's' : ''})`);
  });

  if (categories.length === 0) {
    console.log('   Hint: add images to VRC_PHOTOS or create subfolders and re-run.');
  }
}

build();
