/* ============================================================
   AUTO-GENERATED by generate.js — do not edit directly.
   Run "node generate.js" to rebuild from your folders.
   Data structure: [{ name, label, projects: [{ name, photos: [] }] }]
   ============================================================ */
window.PROJECTS = [
  {
    "name": "UNITY_PROJECTS",
    "label": "Unity Projects",
    "projects": [
      {
        "name": "Dash-Neon",
        "photos": [
          "UNITY_PROJECTS/Dash-Neon/5ieHhx.png",
          "UNITY_PROJECTS/Dash-Neon/AS2xZy.png",
          "UNITY_PROJECTS/Dash-Neon/dGSA1O.png",
          "UNITY_PROJECTS/Dash-Neon/FuPUHV.png",
          "UNITY_PROJECTS/Dash-Neon/J45OxL.png",
          "UNITY_PROJECTS/Dash-Neon/SKcDpF.png"
        ]
      }
    ]
  },
  {
    "name": "VRC_WORLDS",
    "label": "VRChat Worlds",
    "projects": [
      {
        "name": "Afterglow Woods",
        "photos": [
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-43-47.128_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-43-56.344_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-05.455_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-10.657_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-13.562_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-24.802_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-34.474_1920x1080.png",
          "VRC_WORLDS/Afterglow%20Woods/VRChat_2026-08-05_20-44-44.467_1920x1080.png"
        ]
      },
      {
        "name": "Area D",
        "photos": [
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-05.467_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-07.451_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-28.286_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-33.704_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-46.651_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-13-59.123_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-14-02.810_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-14-06.224_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-14-19.851_1920x1080.png",
          "VRC_WORLDS/Area%20D/VRChat_2026-08-05_20-15-18.940_1920x1080.png"
        ]
      },
      {
        "name": "CD3",
        "photos": [
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-11-37.822_1920x1080.png",
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-11-53.555_1920x1080.png",
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-11-57.838_1920x1080.png",
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-12-07.920_1920x1080.png",
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-12-12.711_1920x1080.png",
          "VRC_WORLDS/CD3/VRChat_2026-08-05_20-12-16.577_1920x1080.png"
        ]
      },
      {
        "name": "Den's Apartment",
        "photos": [
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-34-57.893_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-35-23.287_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-35-30.916_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-35-37.566_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-35-47.780_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-35-57.757_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-36-12.248_1920x1080.png",
          "VRC_WORLDS/Den's%20Apartment/VRChat_2026-08-05_19-36-19.279_1920x1080.png"
        ]
      },
      {
        "name": "Dennifer's",
        "photos": [
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-40-54.277_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-41-27.163_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-41-50.610_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-41-59.444_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-07.386_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-14.910_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-16.679_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-20.367_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-23.427_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-36.904_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-39.635_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-42-55.588_1920x1080.png",
          "VRC_WORLDS/Dennifer's/VRChat_2026-08-05_19-43-14.144_1920x1080.png"
        ]
      },
      {
        "name": "Prism Hall",
        "photos": [
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-16-55.114_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-05.102_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-15.755_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-18.854_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-38.436_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-43.402_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-52.840_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-17-57.081_1920x1080.png",
          "VRC_WORLDS/Prism%20Hall/VRChat_2026-08-05_20-18-05.667_1920x1080.png"
        ]
      },
      {
        "name": "Uncle C's Hangout",
        "photos": [
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-01-57.499_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-06.061_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-10.733_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-20.369_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-24.673_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-35.917_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-44.631_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-49.455_1920x1080.png",
          "VRC_WORLDS/Uncle%20C's%20Hangout/VRChat_2026-08-05_20-02-53.862_1920x1080.png"
        ]
      },
      {
        "name": "Volume 128",
        "photos": [
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-38-49.902_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-02.049_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-06.462_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-12.187_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-23.230_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-32.003_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-35.287_1920x1080.png",
          "VRC_WORLDS/Volume%20128/VRChat_2026-08-05_19-39-46.732_1920x1080.png"
        ]
      }
    ]
  }
];
